### PR TITLE
Keep symbolic links on osx-arm64

### LINKED ISSUE #74: wxpython not working on MacOS-ARM64 (M1)
- [X] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

I have installed wxpython using miniforge. wxpython apps will not run in pythonw because that is broken (https://github.com/conda-forge/python.app-feedstock/issues/22), but if I write my own applescript to launch python in a framework, I still hit problems running wxdemo. 

When the app starts, I get a couple of pages with errors like this:
```
objc[2371]: Class wxNSAppController is implemented in both /Users/toby/miniforge3/lib/libwx_osx_cocoau_core-3.1-arm64-apple-darwin20.0.0.dylib (0x105bc0540) and /Users/toby/miniforge3/lib/libwx_osx_cocoau_core-3.1.5.0.0.dylib (0x10711c540). One of the two will be used. Which one is undefined.
```
and 
```
/Users/runner/miniforge3/conda-bld/wxpython_1614965070577/work/ext/wxWidgets/src/common/object.cpp(239): assert "classTable->Get(m_className) == __null" failed in Register(): Class "wxCommandEvent" already in RTTI table - have you used wxIMPLEMENT_DYNAMIC_CLASS() multiple times or linked some object file twice)?
```

finally a window is opened, but is largely blank with this Python error: 
```
Traceback (most recent call last):
  File "/Users/toby/miniforge3/lib/python3.9/site-packages/wx/core.py", line 2326, in Notify
    self.notify()
  File "/Users/toby/miniforge3/lib/python3.9/site-packages/wx/core.py", line 3532, in Notify
    self.result = self.callable(*self.args, **self.kwargs)
  File "/private/tmp/wxPython-demo-4.1.1/demo/Main.py", line 2620, in ShowMain
    frame = wxPythonDemo(None, "wxPython: (A Demonstration)")
  File "/private/tmp/wxPython-demo-4.1.1/demo/Main.py", line 1550, in __init__
    self.ovr = wx.html.HtmlWindow(panel, -1, size=(400, 400))
wx._core.wxAssertionError: C++ assertion ""Assert failure"" failed at /Users/runner/miniforge3/conda-bld/wxpython_1614965070577/work/ext/wxWidgets/src/html/htmlpars.cpp(316) in AddTag(): No HTML tag handlers registered, is your program linked correctly (you might need to use FORCE_WXHTML_MODULES)?
``` 

As a note for anyone also trying to get together Python and wxpython etc in a native Apple Silicon version. wxpython from Homebrew seems to run fine. ~~but see workaround here: https://github.com/Homebrew/homebrew-core/issues/79562~~ (now fixed) 

<br/>
Environment (<code>conda list</code>):
<details>

```
(base) toby@bht21 ~ % conda list
# packages in environment at /Users/toby/mf4.10.1:
#
# Name                    Version                   Build  Channel
backports                 1.0                        py_2    conda-forge
backports.lzma            0.0.14           py39h6167482_3    conda-forge
brotlipy                  0.7.0           py39h46acfd9_1001    conda-forge
ca-certificates           2021.5.30            h4653dfc_0    conda-forge
certifi                   2021.5.30        py39h2804cbe_0    conda-forge
cffi                      1.14.5           py39h702c04f_0    conda-forge
chardet                   4.0.0            py39h2804cbe_1    conda-forge
conda                     4.10.1           py39h2804cbe_0    conda-forge
conda-package-handling    1.7.3            py39h5161555_0    conda-forge
cryptography              3.4.7            py39h73257c9_0    conda-forge
expat                     2.4.1                hbdafb3b_0    conda-forge
gettext                   0.19.8.1          hea66d9f_1005    conda-forge
idna                      2.10               pyh9f0ad1d_0    conda-forge
jpeg                      9d                   h27ca646_0    conda-forge
libcxx                    11.1.0               h168391b_0    conda-forge
libffi                    3.3                  h9f76cd9_2    conda-forge
libiconv                  1.16                 h642e427_0    conda-forge
libpng                    1.6.37               hf7e6567_2    conda-forge
ncurses                   6.2                  h9aa5885_4    conda-forge
openssl                   1.1.1k               h27ca646_0    conda-forge
pathlib2                  2.3.5            py39h2804cbe_3    conda-forge
pip                       21.1.2             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               h27ca646_1001    conda-forge
pycosat                   0.6.3           py39h46acfd9_1006    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pypubsub                  4.0.3                      py_0    conda-forge
pysocks                   1.7.1            py39h2804cbe_3    conda-forge
python                    3.9.5           h54d631c_0_cpython    conda-forge
python.app                1.3              py39hf68e5b1_4    conda-forge
python_abi                3.9                      1_cp39    conda-forge
readline                  8.1                  hedafd6a_0    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
ruamel_yaml               0.15.80         py39h46acfd9_1004    conda-forge
setuptools                49.6.0           py39h2804cbe_3    conda-forge
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.36.0               h72a2b83_0    conda-forge
tk                        8.6.10               hf7e6567_1    conda-forge
tqdm                      4.61.1             pyhd8ed1ab_0    conda-forge
tzdata                    2021a                he74cb21_0    conda-forge
urllib3                   1.26.5             pyhd8ed1ab_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wxpython                  4.1.1            py39h28cb02c_1    conda-forge
xz                        5.2.5                h642e427_1    conda-forge
yaml                      0.2.5                h642e427_0    conda-forge
zlib                      1.2.11            h31e879b_1009    conda-forge
(base) toby@bht21 ~ % 


```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
(base) toby@bht21 ~ % conda info

     active environment : base
    active env location : /Users/toby/mf4.10.1
            shell level : 1
       user config file : /Users/toby/.condarc
 populated config files : /Users/toby/mf4.10.1/.condarc
                          /Users/toby/.condarc
          conda version : 4.10.1
    conda-build version : not installed
         python version : 3.9.5.final.0
       virtual packages : __osx=11.2.3=0
                          __unix=0=0
                          __archspec=1=arm64
       base environment : /Users/toby/mf4.10.1  (writable)
      conda av data dir : /Users/toby/mf4.10.1/etc/conda
  conda av metadata url : https://repo.anaconda.com/pkgs/main
           channel URLs : https://conda.anaconda.org/conda-forge/osx-arm64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/toby/mf4.10.1/pkgs
                          /Users/toby/.conda/pkgs
       envs directories : /Users/toby/mf4.10.1/envs
                          /Users/toby/.conda/envs
               platform : osx-arm64
             user-agent : conda/4.10.1 requests/2.25.1 CPython/3.9.5 Darwin/20.3.0 OSX/11.2.3
                UID:GID : 3328:1113
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by bkpoon**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

Fixes #74

During the build stage on `osx-arm64`, `cctools-port` is generating signatures which causes symbolically linked files to become actual files. This causes issues at runtime (#74). The environment variable, `NO_CODESIGN`, disables code signing (https://github.com/tpoechtrager/cctools-port/blob/master/cctools/include/stuff/port.h) during the building stage. The libraries are still signed during the packaging stage.

### CODE REVIEW

**Comment by bkpoon** [comment]
@conda-forge-admin, please rerender

File: recipe/build.sh [hunk 1]
```diff
@@ -47,6 +47,15 @@ fi
...
 
+# Disable code signing during the building stage on osx-arm64
+# The code signing in cctools-port is causing the symbolically linked
+# libraries in $PREFIX/lib to become files which causes issues at runtime
+# https://github.com/conda-forge/wxpython-feedstock/issues/74
+# The environment variable disables the step (defined in cctools-port/cctools/include/stuff/port.h)
+# The libraries are still signed during the packaging stage
+if [[ "$CC" == *"arm64"* ]]; then
+  export NO_CODESIGN=1
+fi
```
Comment (ocefpaf) [inline recipe/build.sh:58]: Feedback I got from Isuru on this :

> That should be fine. Better to double check that the package works on osx-arm64
Opening an issue at https://github.com/thefloweringash/sigtool to follow symlinks would be good

@bkpoon I'm assuming you already tested it, right? Can you also open that issue to report the problem to sigtool?

Comment (bkpoon) [reply recipe/build.sh:58]: Yes, I tested the import from #74 and I tested my own GUI that uses wxPython on Apple Silicon. My GUI does not use every feature of wxPython, though. But I did check the `${CONDA_PREFIX}/lib` directories in the Python 3.8 package for both `osx-64` and `osx-arm64` and they both look similar in terms of symbolic links.

And I'll work on a simple reproducer and create an issue for `sigtool`.

Thanks!

**Comment by bkpoon** [comment]
Created https://github.com/thefloweringash/sigtool/issues/10

Running `codesign -s - -f <symbolic link>` will replace the symbolic link with the file. I tested this by creating a new environment with the `sigtool` and `wxpython` packages. Then I ran `codesign` on one of the symbolic link in `${CONDA_PREFIX}/lib`.

File: recipe/build.sh (hunk 1 above)
Comment (ocefpaf) [reply recipe/build.sh:58]: Thanks!
